---
- name: Install packages
  apt: name={{ item }}
  with_items:
    - imagemagick
    - libmagickwand-dev

- name: Install rmagick gem
  command: bash -lc "gem install rmagick"
  sudo_user: '{{ user_name }}'