---
- hosts: all
  gather_facts: no
  roles:
    - swap
    - { role: apt_proxy, when: use_apt_proxy }
    - base
    - rbenv
    - ruby
    - sqlite
    - mysql
    - postgresql
    - rmagick
    - vim
  tasks:
    - apt: update_cache=yes