---
vm_swap: 512

use_apt_proxy: false

# Additional packages
packages:
  - curl
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - nodejs

# Server config
server_name: localhost
user_name: vagrant
group_name: vagrant
user_home_path: '/home/{{ user_name }}'

rbenv_path: '{{ user_home_path }}/.rbenv'
rbenv_bin: '{{ rbenv_path }}/bin/rbenv'

# Ruby and Rails
rails_version: '~> 4.2'
ruby_version: 2.2.0
environment_file: /vagrant/.envrc

default_db_name: myapp
default_db_password: 123456

#MySQL
mysql_db_user: '{{user_name}}'
mysql_db_password: '{{default_db_password}}'
mysql_db_name: '{{default_db_name}}'

#PostgreSQL
postgresql_db_user: '{{user_name}}'
postgresql_db_password: '{{default_db_password}}'
postgresql_db_name: '{{default_db_name}}'